const defaultTheme = require("tailwindcss/defaultTheme");

/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}"],
  safelist: [
    "bg-orange",
    "bg-blue",
    "bg-red",
    "bg-dark-green",
    "bg-green",
    "bg-yellow",
    "bg-purple",
    "border-orange-border",
    "border-blue-border",
    "border-red-border",
    "border-dark-green-border",
    "border-green-border",
    "border-yellow-border",
    "border-purple-border",
    "[filter:drop-shadow(5px_5px_5px_theme('colors.dark-green-border'))]",
    "[filter:drop-shadow(5px_5px_5px_theme('colors.green-border'))]",
    "[filter:drop-shadow(5px_5px_5px_theme('colors.yellow-border'))]",
    "[filter:drop-shadow(5px_5px_5px_theme('colors.purple-border'))]",
    "[filter:drop-shadow(5px_5px_5px_theme('colors.orange-border'))]",
    "[filter:drop-shadow(5px_5px_5px_theme('colors.blue-border'))]",
    "[filter:drop-shadow(5px_5px_5px_theme('colors.red-border'))]",
  ],
  theme: {
    extend: {
      fontFamily: {
        sans: ["Dosis", ...defaultTheme.fontFamily.sans],
        "space-grotesk": [
          "Space Grotesk",
          "Dosis",
          ...defaultTheme.fontFamily.sans,
        ],
      },
      colors: {
        bgc: "#080404",
        border: "rgba(89, 89, 89, 0.75)",
        orange: "#FDB03C",
        "orange-border": "#C97800",
        blue: "#3CC3FD",
        "blue-border": "#0083BB",
        red: "#FF6363",
        "red-border": "#C30000",
        "dark-green": "#2E8F00",
        "dark-green-border": "#1A5000",
        green: "#3CFDA0",
        "green-border": "#00B05C",
        yellow: "#FFE920",
        "yellow-border": "#7D7100",
        purple: "#FF3AF7",
        "purple-border": "#A0009A",
      },
    },
  },
  plugins: [],
};
